version: "3"

services:

  app:
    build: php-fpm/
    container_name: app
    volumes:
      - "./..:/var/www"
    networks:
      - net

  nginx:
    build: nginx/
    restart: always
    tty: true
    ports:
      - "8585:80"
    volumes:
      - "./..:/var/www"
    container_name: nginx
    networks:
      - net

  redis:
    image: redis
    ports:
      - 6379
    container_name: redis
    networks:
      - net

networks:
  net:
    driver: bridge