version: "2.3"

services:

  app:
    build: php-fpm/
    container_name: app
    entrypoint: dockerize -wait tcp://192.168.1.113:3316 -timeout 40s /var/www/infrastructure/php-fpm/Entrypoint.sh
    volumes:
      - "./..:/var/www"
    networks:
      - net
    depends_on: 
      - db

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./../dbdata:/var/lib/mysql
    ports:
      - "3316:3306"
    environment: 
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - net
        
  nginx:
    build: nginx/
    restart: always
    tty: true
    ports:
      - "8585:80"
    volumes:
      - "./..:/var/www"
    container_name: nginx
    networks:
      - net

  redis:
    image: redis
    ports:
      - 6379
    container_name: redis
    networks:
      - net

networks:
  net:
    driver: bridge